### ISSUE TITLE
webpack build error: document is not defined

### ISSUE THREAD

**Issue by fxbabys** [donavon/use-dark-mode#14]
I am planning to add dark mode for my website and import this package, it works in development but when building it throws an error: document is not defined. I tried to pass the optioalConfigObject but still get the error.

**Comment by donavon** [comment]
Do me a favor. Try this out with version 2.1.2. I have a small fix that used `global.document` vs just `document`.

**Comment by fxbabys** [comment]
Now the error is: Cannot read property 'body' of undefined.

**Comment by wKovacs64** [comment]
This is happening in SSR/SSG tools because `document` isn't available in Node (where this code runs at build-time). Some options:

- add a `typeof document !== 'undefined'` check around the `element` assignment in `defaultConfig` (or wrap the assignment in a try-catch and let the error fall on the floor, etc.)
- change `element` from an actual element to a selector string on which you later call `document.querySelector` once it's safe to do so (`setDOMClass` maybe, since that only gets called from within the `useEffect`?)

I'd probably lean towards the first approach as it doesn't change your public API. Maybe there are better solutions?

Note: this will be a problem in `use-persisted-state` [as](https://github.com/donavon/use-persisted-state/blob/8744c7774b924f1e1f9e5460011f3cd5e2c2a302/src/index.js#L29) [well](https://github.com/donavon/use-persisted-state/blob/8744c7774b924f1e1f9e5460011f3cd5e2c2a302/src/index.js#L44) since `localStorage` is not available either.

**Comment by donavon** [comment]
@wKovacs64,

looking to do this in `useDarkMode`

```js
const noop = () => {};

const defaultElement = (global.document && global.document.body) || {
  classList: {
    add: noop,
    remove: noop,
  },
};

const defaultConfig = {
  classNameDark: defaultClassNameDark,
  classNameLight: defaultClassNameLight,
  element: defaultElement,
};
```

basically, this will provide a mock `classList` object with `add` and `remove` methods if `global.document.body` doesn't exist.

Thoughts?

But before I do, I have to fix `use-persisted-state` to support SSR as well.

**Comment by wKovacs64** [comment]
I [suggested](https://github.com/soyguijarro/react-storage-hooks/issues/1#issue-393545804) that type of approach in a similar project a while back but now I'm not sure it really matters. Whatever is cleanest/easiest to maintain is probably fine since all we're doing is faking it out to make it build.

Hmm, the no-flash solution might be in jeopardy here. 🤔

**Comment by donavon** [comment]
the no-flash code _only_ runs client-side as it's included in `index.html`, so no issues there.

**Comment by wKovacs64** [comment]
I was thinking it might get evaluated during build but it shouldn't. 👍 

(For a lot of these SSR/SSG tools, there isn't an `index.html` to modify. It's generated, so we just pass in some custom JSX.)

**Comment by donavon** [comment]
@fxbabys 

I've create an alpha for you to test against. Test it by installing:

```
npm i use-dark-mode@next
```

I tested it myself with an SSR test app, but would like you to verify before I put the code into the `@latest` version.

**Comment by fxbabys** [comment]
It works now, and I can also override the default config. Thank you !

**Comment by donavon** [comment]
nice! I'll create a real `@latest` version 2.2.0 and publish it tomorrow. Thx fo reporting this and working with me to get it tested.

@allcontributors[bot] please add @fxbabys for userTesting and bug

**Comment by donavon** [comment]
@allcontributors[bot] please add ideas to @wKovacs64

**Comment by donavon** [comment]
arrg. merge conflict. again...

@allcontributors[bot] please add ideas to @wKovacs64

**Comment by donavon** [comment]
one more time...

@allcontributors[bot] please add ideas to @wKovacs64

**Comment by wKovacs64** [comment]
I don't think that worked. 😄 (The bot, I mean. The changes in `@next` work!)

**Comment by donavon** [comment]
yeah. the bot is a little finicky.  i'll have to manually back it out and add `ideas`. 🤦‍♂️

**Comment by jakebolam** [comment]
Hey! Thanks for using the bot :)

I think it's [expecting the syntax](https://allcontributors.org/docs/en/bot/usage#all-contributors-add) `bot please add username for blah` we're [working on improving this](https://github.com/all-contributors/all-contributors-bot/pull/127), and [auto fixing merge conflicts](https://github.com/all-contributors/all-contributors-bot/issues/62) 😀

**Comment by donavon** [comment]
@fxbabys 

I pushed the SSR support into 2.2.1 (latest). Can you please just verify that it still works for you.

Thx!

**Comment by fxbabys** [comment]
Sure, and it still works. 😄
